version: '3.9'
services:
  development:
    container_name: app-05-firebase-api
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - /workspaces/app-05-firebase-api/node_modules
